# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenapp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickenapp1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ee4f836c8e064ff7b73432726854a6ac }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6c8a79d512854990addbc2be0c3334dd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickenapp1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ee4f836c8e064ff7b73432726854a6ac }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenapp1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ee3e77c5693c4659bd58d8134712d340 }}
        images: 'chickenapp1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ee4f836c8e064ff7b73432726854a6ac }}/chicken:${{ github.sha }}'